[book]
language = "en"
multilingual = false
src = "src"
title = "NixOS-WSL"

[output.html]
additional-css = ["custom.css"]
additional-js = ["custom.js"]
edit-url-template = "https://github.com/nix-community/nixos-wsl/tree/main/docs/{path}"
git-repository-url = "https://github.com/nix-community/nixos-wsl"
