name: "Release"

on:
  push:
    tags: []

jobs:
  build:
    name: Build ðŸ› ï¸
    uses: ./.github/workflows/run_build.yml

  package:
    name: Package ðŸ“¦
    uses: ./.github/workflows/run_package.yml
    needs:
      - build
    secrets:
      APPX_SIGNING_CERT: ${{ secrets.APPX_SIGNING_CERT }}
      CERT_ALGORITHM: ${{ secrets.CERT_ALGORITHM }}

  release:
    needs:
      - build
      - package
    name: Create Release ðŸ“¢
    runs-on: ubuntu-latest
    steps:
      - name: Download Tarball ðŸ“¥
        uses: actions/download-artifact@v4
        with:
          name: tarball

      - name: Download bundle
        uses: actions/download-artifact@v4
        with:
          name: launcher-bundle
          path: launcher-bundle

      - name: Zip launcher bundle ðŸ“¦
        working-directory: launcher-bundle
        run: zip -r ../NixOS-WSL-Launcher.zip .

      - name: Generate Checksums ðŸ”‘
        run: |
          for x in *.{tar.gz,zip}; do
            sha256sum $x > ${x}.sha256
          done

      - name: Attach to Release ðŸ“Ž
        uses: softprops/action-gh-release@v2
        with:
          files: |
            nixos-wsl.tar.gz
            nixos-wsl.tar.gz.sha256
            NixOS-WSL-Launcher.zip
            NixOS-WSL-Launcher.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
