name: "Release"

on:
  push:
    tags: []

jobs:
  build:
    name: Build ðŸ› ï¸
    uses: ./.github/workflows/run_build.yml

  package:
    name: Package ðŸ“¦
    uses: ./.github/workflows/run_package.yml
    needs:
      - build
    secrets:
      APPX_SIGNING_CERT: ${{ secrets.APPX_SIGNING_CERT }}
      CERT_ALGORITHM: ${{ secrets.CERT_ALGORITHM }}

  release:
    needs:
      - build
      - package
    name: Create Release ðŸ“¢
    runs-on: ubuntu-latest
    steps:
      - name: Download Tarball ðŸ“¥
        uses: actions/download-artifact@v4

      - name: Download appx ðŸ“¥
        uses: actions/download-artifact@v4
        with:
          name: appx

      - name: Rename appx âœï¸
        run: mv */*.msixbundle NixOS-WSL.msixbundle

      - name: Generate Checksums ðŸ”‘
        run: |
          mv tarball-modern/nixos-wsl.tar.gz nixos-wsl.tar.gz
          mv tarball-legacy/nixos-wsl.tar.gz nixos-wsl-legacy.tar.gz
          for x in *.{tar.gz,msixbundle}; do
            sha256sum $x > ${x}.sha256
          done

      - name: Attach to Release ðŸ“Ž
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nixos-wsl.tar.gz
            nixos-wsl.tar.gz.sha256
            nixos-wsl-legacy.tar.gz
            nixos-wsl-legacy.tar.gz.sha256
            NixOS-WSL.msixbundle
            NixOS-WSL.msixbundle.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
