name: Validate Tarball

on:
  workflow_call: {}

jobs:
  validate:
    name: Validate Tarball ðŸ©º
    runs-on: ubuntu-latest
    steps:
      - name: Checkout WSL Repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          repository: microsoft/WSL
          ref: 2.6.1

      - name: Install dependencies ðŸ“¦
        shell: bash
        run: |
          pip3 install -r distributions/requirements.txt

      - name: Download Tarball ðŸ“¥
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: tarball

      - name: Validate Tarball ðŸ©º
        shell: bash
        run: |
          python3 distributions/validate-modern.py --tar nixos.wsl
